[package]
name = "browser-windows-nwg"
version = "0.1.0"
edition = "2021"
license.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
native-windows-gui = { version = "1.0", default-features = false, features = ["listbox", "combobox", "frame", "number-select"] }
native-windows-derive = "1.0"
windows = { version = "0.62", features = ["Win32_Foundation"] }
winapi = "0.3"
render-engine = { path = "../render-engine" }
browser-core = { path = "../browser-core" }
anyhow = "1"
