[workspace]
resolver = "2"
members = [
    "crates/render-engine",
    "crates/browser-core",
    "crates/browser-chrome-core",
    "crates/browser-linux-gtk3",
    "crates/browser-windows-winui",
    "crates/browser-windows-reactor",
    "crates/browser-macos-appkit",
]

[workspace.package]
license = "MIT OR Apache-2.0"
